
name: "Coding Standards"

on:
  pull_request:
    branches:
      - "*.x"
  push:
    branches:
      - "*.x"

jobs:
  coding-standards:
    uses: "doctrine/.github/.github/workflows/coding-standards.yml@use_a_valid_ref_here"
